"""finally

Revision ID: 404d2d40931f
Revises: 625b07841dfa
Create Date: 2026-05-31 16:17:20.048142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '404d2d40931f'
down_revision: Union[str, Sequence[str], None] = '625b07841dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'test_field')
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
